# TCL File Generated by Component Editor 10.0
# Thu Jul 08 21:36:45 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | TERASIC_SRAM "TERASIC_SRAM" v1.0
# | null 2010.07.08.21:36:45
# | 
# | 
# | E:/DE2_115_NEW/trunk/ref_design/DE2_115_NIOS_HOST_MOUSE_VGA/ip/TERASIC_SRAM/TERASIC_SRAM.v
# | 
# |    ./TERASIC_SRAM.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module TERASIC_SRAM
# | 
set_module_property NAME TERASIC_SRAM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Terasic Technologies Inc./DE2_115"
set_module_property DISPLAY_NAME TERASIC_SRAM
set_module_property TOP_LEVEL_HDL_FILE TERASIC_SRAM.v
set_module_property TOP_LEVEL_HDL_MODULE TERASIC_SRAM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file TERASIC_SRAM.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DATA_BITS INTEGER 16
set_parameter_property DATA_BITS DEFAULT_VALUE 16
set_parameter_property DATA_BITS DISPLAY_NAME DATA_BITS
set_parameter_property DATA_BITS TYPE INTEGER
set_parameter_property DATA_BITS UNITS None
set_parameter_property DATA_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_BITS AFFECTS_GENERATION false
set_parameter_property DATA_BITS HDL_PARAMETER true
add_parameter ADDR_BITS INTEGER 20
set_parameter_property ADDR_BITS DEFAULT_VALUE 20
set_parameter_property ADDR_BITS DISPLAY_NAME ADDR_BITS
set_parameter_property ADDR_BITS TYPE INTEGER
set_parameter_property ADDR_BITS UNITS None
set_parameter_property ADDR_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_BITS AFFECTS_GENERATION false
set_parameter_property ADDR_BITS HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ASSOCIATED_CLOCK clock_reset
set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock_reset
set_interface_property avalon_slave associatedReset clock_reset_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice true
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave s_chipselect_n chipselect_n Input 1
add_interface_port avalon_slave s_write_n write_n Input 1
add_interface_port avalon_slave s_address address Input ADDR_BITS
add_interface_port avalon_slave s_read_n read_n Input 1
add_interface_port avalon_slave s_writedata writedata Input DATA_BITS
add_interface_port avalon_slave s_readdata readdata Output DATA_BITS
add_interface_port avalon_slave s_byteenable_n byteenable_n Input DATA_BITS/8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end SRAM_DQ export Bidir DATA_BITS
add_interface_port conduit_end SRAM_ADDR export Output ADDR_BITS
add_interface_port conduit_end SRAM_UB_n export Output 1
add_interface_port conduit_end SRAM_LB_n export Output 1
add_interface_port conduit_end SRAM_WE_n export Output 1
add_interface_port conduit_end SRAM_CE_n export Output 1
add_interface_port conduit_end SRAM_OE_n export Output 1
# | 
# +-----------------------------------
