# TCL File Generated by Component Editor 11.1sp2
# Fri Nov 30 14:50:58 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | CY7C67200_IF "CY7C67200_IF" v1.0
# | Peli 2012.11.30.14:50:58
# | cy7c67200 hpi controller
# | 
# | D:/SVN/DE2_115_CYPRESS/DEV/peli/DE2_115_NIOS_HOST_MOUSE_VGA/ip/TERASIC_CY7C67200/CY7C67200_IF.v
# | 
# |    ./CY7C67200_IF.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module CY7C67200_IF
# | 
set_module_property DESCRIPTION "cy7c67200 hpi controller"
set_module_property NAME CY7C67200_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc./DE2_115"
set_module_property AUTHOR Peli
set_module_property DISPLAY_NAME CY7C67200_IF
set_module_property TOP_LEVEL_HDL_FILE CY7C67200_IF.v
set_module_property TOP_LEVEL_HDL_MODULE CY7C67200_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file CY7C67200_IF.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point hpi
# | 
add_interface hpi avalon end
set_interface_property hpi addressUnits WORDS
set_interface_property hpi associatedClock clock_sink
set_interface_property hpi associatedReset clock_sink_reset
set_interface_property hpi bitsPerSymbol 8
set_interface_property hpi burstOnBurstBoundariesOnly false
set_interface_property hpi burstcountUnits WORDS
set_interface_property hpi explicitAddressSpan 0
set_interface_property hpi holdTime 180
set_interface_property hpi linewrapBursts false
set_interface_property hpi maximumPendingReadTransactions 0
set_interface_property hpi readLatency 0
set_interface_property hpi readWaitStates 180
set_interface_property hpi readWaitTime 180
set_interface_property hpi setupTime 180
set_interface_property hpi timingUnits Nanoseconds
set_interface_property hpi writeWaitStates 180
set_interface_property hpi writeWaitTime 180

set_interface_property hpi ENABLED true

add_interface_port hpi oDATA readdata Output 32
add_interface_port hpi iADDR address Input 2
add_interface_port hpi iRD_N read_n Input 1
add_interface_port hpi iWR_N write_n Input 1
add_interface_port hpi iCS_N chipselect_n Input 1
add_interface_port hpi iDATA writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 10000000

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_reset
# | 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT

set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset iRST_N reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint hpi
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset clock_sink_reset

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender oINT irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end HPI_DATA export Bidir 16
add_interface_port conduit_end HPI_ADDR export Output 2
add_interface_port conduit_end HPI_RD_N export Output 1
add_interface_port conduit_end HPI_WR_N export Output 1
add_interface_port conduit_end HPI_CS_N export Output 1
add_interface_port conduit_end HPI_RST_N export Output 1
add_interface_port conduit_end HPI_INT export Input 1
# | 
# +-----------------------------------
