# TCL File Generated by Component Editor 9.1sp1
# Fri Feb 26 13:49:35 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SEG7_IF "SEG7_IF" v1.0
# | null 2010.02.26.13:49:35
# | 
# | 
# | D:/svn/de2_115_golden_sopc/ip/TERASIC_SEG7/SEG7_IF.v
# | 
# |    ./SEG7_IF.v syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module SEG7_IF
# | 
set_module_property DESCRIPTION ""
set_module_property NAME SEG7_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Terasic Technologies Inc./DE2_115"
set_module_property DISPLAY_NAME SEG7_IF
set_module_property TOP_LEVEL_HDL_FILE SEG7_IF.v
set_module_property TOP_LEVEL_HDL_MODULE SEG7_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SEG7_IF.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter SEG7_NUM INTEGER 8 ""
set_parameter_property SEG7_NUM DEFAULT_VALUE 8
set_parameter_property SEG7_NUM DISPLAY_NAME SEG7_NUM
set_parameter_property SEG7_NUM UNITS None
set_parameter_property SEG7_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SEG7_NUM DESCRIPTION ""
set_parameter_property SEG7_NUM DISPLAY_HINT ""
set_parameter_property SEG7_NUM AFFECTS_GENERATION false
set_parameter_property SEG7_NUM HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 3 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 3
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH DISPLAY_HINT ""
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DEFAULT_ACTIVE INTEGER 1 ""
set_parameter_property DEFAULT_ACTIVE DEFAULT_VALUE 1
set_parameter_property DEFAULT_ACTIVE DISPLAY_NAME DEFAULT_ACTIVE
set_parameter_property DEFAULT_ACTIVE UNITS None
set_parameter_property DEFAULT_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_ACTIVE DESCRIPTION ""
set_parameter_property DEFAULT_ACTIVE DISPLAY_HINT ""
set_parameter_property DEFAULT_ACTIVE AFFECTS_GENERATION false
set_parameter_property DEFAULT_ACTIVE HDL_PARAMETER true
add_parameter LOW_ACTIVE INTEGER 1 ""
set_parameter_property LOW_ACTIVE DEFAULT_VALUE 1
set_parameter_property LOW_ACTIVE DISPLAY_NAME LOW_ACTIVE
set_parameter_property LOW_ACTIVE UNITS None
set_parameter_property LOW_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LOW_ACTIVE DESCRIPTION ""
set_parameter_property LOW_ACTIVE DISPLAY_HINT ""
set_parameter_property LOW_ACTIVE AFFECTS_GENERATION false
set_parameter_property LOW_ACTIVE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave s_address address Input ADDR_WIDTH
add_interface_port avalon_slave s_read read Input 1
add_interface_port avalon_slave s_readdata readdata Output 8
add_interface_port avalon_slave s_write write Input 1
add_interface_port avalon_slave s_writedata writedata Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end SEG7 export Output SEG7_NUM*8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink s_reset reset Input 1
add_interface_port clock_sink s_clk clk Input 1
# | 
# +-----------------------------------
